### ISSUE TITLE
Index Error in main_demo

### ISSUE THREAD

**Issue by MRudey** [vonera/FEM_GPD#1]
Hi,
I am trying to get the main_demo.m to run. But it fails with the following Errors:
```
Index in position 1 exceeds array bounds (must not exceed 2).

Error in Models.MCMC.GPD.Input (line 47)
            self.ut_ksi = [ ones(1,size(ut,2)) ; ut(meta.umask_ksi,:)];

Error in Models.MCMC.Factory/createInput (line 101)
                input = Models.MCMC.GPD.Input(meta, xt, ut);

Error in Core.Construction.Factory.createInput (line 95)
            input = mfac.createInput(cfg, xt, ut, meta);

Error in Core.Datatypes.InputHandler/get (line 71)
                input(j) = Core.Construction.Factory.createInput(self.cfg, self.xt{j}, self.ut{j}, self.meta_cell{idx});

Error in Core.ModelFit/fit (line 50)
                input = iHandl.get(i);

Error in FEM.fit (line 63)
            resultHandler = mf.fit(inputHandler);

Error in main_demo (line 53)
    rHandler = FEM.fit(iHandler);
```

Apparently it tries to index `ut` with `meta.umask_ksi` which in my case is `[3, 5, 7, 8, 11]` while `ut` is a 2x1000 double? I have not looked into further details yet because I was just playing around with the toolbox.

I had another error before I ran into this one which was apparently related with the compilation of the mex files. Therefore, I compiled `MEX_GPDestimate.cpp` with the options `-lgsl -lgslcblas` because `cblas_ctrmv` was undefined if only `-lgsl` was used.

_My system configuration (just in case):_
Ubuntu 20.10
Matlab R2020a

**Comment by gulgosha** [comment]
Hi Michael, 

to run the demo please use the unmodified `FEM_GPD/demo/adjustCFG.m`, which contains the correct mask for the parameters. 

For the demo `ut` has 2 dimensions, please check here the function `FEM_GPD/demo/generate.m`,  thus in demo the mask index should not increase 2, for both, `ksi` and `si`.  Possible combinations could be:  `{[1 ], [2], [], [1, 2] }`. 
If you change in `FEM_GPD/demo/adjustCFG.m` lines 13-14 to:
`cfg.model.ut_combis{1} ={[1 ], [2], [], [1, 2] }; `
`cfg.model.ut_combis{2} ={[1 ], [2], [], [1, 2] }; `
FEM-GPD will run over all four combinations and return a the best result wrt AICc. 

Please let us know if it works. 

PS: Thanks for pointing to the issue with -lgsl. We will check that.

**Comment by MRudey** [comment]
Yes this worked. Thanks for your swift reply!

I did not modify `FEM_GPD/demo/adjustCFG.m`. Originally it was:
```
cfg.model.ut_combis{1} = {[1 2]}; % cell of arrays: {[1 2 3], [2 3 4], [] } ...
cfg.model.ut_combis{2} = {[]}; 
```
Maybe my MATLAB was confused by the other `adjustCFG.m` that mirrors it in the swiss_precipitation folder.
